<?php
namespace backend\models;

use yii\base\ActionFilter;
use yii\web\ForbiddenHttpException;

class RbacFilter extends ActionFilter {

    public function beforeAction($action){
    if(\Yii::$app->user->isGuest){
        return $action->controller->redirect(\Yii::$app->user->loginUrl);
    }
        //var_dump(\Yii::$app->user->id);
        //var_dump($action->uniqueId);
        //var_dump(\Yii::$app->user->can($action->uniqueId));exit;
        if (!\Yii::$app->user->can($action->uniqueId)){
        throw new ForbiddenHttpException('您没有访问权限');
    }
     return parent::beforeAction($action); // TODO: Change the autogenerated stub
}


}